<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 18:55:06
?>
<h1>Institution</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Code</th>
  <th>Name</th>
  <th>Created at</th>
  <th>Updated at</th>
</tr>
</thead>
<tbody>
<?php foreach ($institutions as $institution): ?>
<tr>
    <td><?php echo $institution->getId()?>
    <td><?php echo link_to($institution->getCode(), 'institution/show?id='.$institution->getId()) ?></td>
      <td><?php echo $institution->getName() ?></td>
      <td><?php echo $institution->getCreatedAt() ?></td>
      <td><?php echo $institution->getUpdatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<div id="button">
<?php echo link_to ('Create', 'institution/create') ?> &nbsp; <?php echo link_to ('Import from CSV', 'import/index?target_model=Institution'); ?>
</div>
