<?php
// auto-generated by sfPropelCrud
// date: 2008/06/28 16:36:40
?>
<?php 
use_helper('Object'); 
use_helper('Bootstrap');
?>

<?php if ($sf_request->hasParameter('id')): ?>
<h1>Edit Debater</h1>
<?php else: ?>
<h1>Create Debater</h1>
<?php endif; ?>

<?php if ($sf_request->hasErrors()): ?>
<div class="alert-message error">There were errors in the submitted data.</div>
<?php endif; ?>

<?php echo form_tag('debater/update') ?>
  <?php echo object_input_hidden_tag($debater, 'getId') ?>
  <fieldset>
    <!-- Name input field -->
    <?php echo bootstrap_stateful_form_control('name', 'Name', object_input_tag($debater, 'getName', array ('size' => 20, 'id' => 'name', "name" => "name", 'class' => 'xlarge')), array("error" => $sf_request->getErrors())); ?>
    <!-- Team select box -->
    <?php echo bootstrap_stateful_form_control('team_id', 'Team', object_select_tag($debater, 'getTeamId', array ('related_class' => 'Team', 'text_method' => 'getName')), array("error" => $sf_request->getErrors())); ?>
  </fieldset>
  <div id="button">
    <?php echo submit_tag('Save', array('class' => 'btn primary')) ?>
    <?php if ($debater->getId()): ?>
        &nbsp;<?php echo link_to('Delete', 'debater/delete?id='.$debater->getId(), array('post' => true, 'confirm' => 'Are you sure?', 'class' => 'btn danger')) ?>
        &nbsp;<?php echo link_to('Cancel', 'debater/show?id='.$debater->getId(), array('class' => 'btn')) ?>
    <?php else: ?>
        &nbsp;<?php echo link_to('Cancel', 'debater/list', array('class' => 'btn')) ?>
    <?php endif; ?>
</div>
</form>
