<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 18:55:06
?>

<h1>View Institution</h1>
<hr />
<table id="form">
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $institution->getId() ?></td>
</tr>
<tr>
<th>Code: </th>
<td><?php echo $institution->getCode() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $institution->getName() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $institution->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $institution->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<div id="button">
<?php echo link_to('Edit', 'institution/edit?id='.$institution->getId()) ?>
&nbsp;<?php echo link_to('List', 'institution/list') ?>
</div>
