<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 19:00:01
?>

<?php use_helper('Object') ?>

<?php echo form_tag('round/enterScores2') ?>

<h1> Select a debate venue </h1>
<table>
<tbody>
<tr>
	<td>
		<?php 
			$debates = $round->getUnscoredDebates();
			echo select_tag('debate', objects_for_select($debates, 'getId', 'getDebateInfo'));
		?>

	</td>
</tr>


</tbody>
</table>
<?php echo submit_tag('select') ?>

