<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 19:00:01
?>
<h1>Round</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Name</th>
  <th>Type</th>
  <th>Preceded by round</th>
  <th>Feedback weightage</th>
  <th>Created at</th>
  <th>Updated at</th>
</tr>
</thead>
<tbody>
<?php foreach ($rounds as $round): ?>
<tr>
    <td><?php echo link_to($round->getId(), 'round/show?id='.$round->getId()) ?></td>
      <td><?php echo $round->getName() ?></td>
      <td><?php echo $round->getType() ?></td>
      <td><?php echo $round->getPrecededByRoundId() ?></td>
	  <td><?php echo $round->getFeedbackWeightage() ?></td>
      <td><?php echo $round->getCreatedAt() ?></td>
      <td><?php echo $round->getUpdatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
<div id="button">
<?php echo link_to ('Create', 'round/create') ?>
</div>