<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 19:00:01
?>
<h1>View Round</h1>

<?php if ($sf_flash->has("success")): ?>
<div class="alert-message success">
    <?php echo $sf_flash->get("success"); ?>
</div>
<?php endif; ?>

<div class="row">
    <div class="span-one-third"><strong>Id</strong></div>
    <div class="span-two-thirds"><?php echo $round->getId(); ?></div>
</div>
<div class="row">
    <div class="span-one-third"><strong>Name</strong></div>
    <div class="span-two-thirds"><?php echo $round->getName(); ?></div>
</div>
<div class="row">
    <div class="span-one-third"><strong>Type</strong></div>
    <div class="span-two-thirds"><?php echo $round->getTypeText(); ?></div>
</div>
<div class="row">
    <div class="span-one-third"><strong>Preceded by round</strong></div>
    <div class="span-two-thirds"><?php echo $round->getPrecededByRoundId() > 0 ? link_to($round->getRoundRelatedByPrecededByRoundId()->getName(), 'round/show?id=' . $round->getPrecededByRoundId()) : '&nbsp;'; ?></div>
</div>
<div class="row">
    <div class="span-one-third"><strong>Feedback weightage</strong></div>
    <div class="span-two-thirds"><?php echo $round->getFeedbackWeightage() ?></div>
</div>
<div class="row">
    <div class="span-one-third"><strong>Created at</strong></div>
    <div class="span-two-thirds"><?php echo $round->getCreatedAt() ?></div>
</div>
<div class="row">
    <div class="span-one-third"><strong>Updated at</strong></div>
    <div class="span-two-thirds"><?php echo $round->getUpdatedAt() ?></div>
</div>
<div id="button">
<?php echo link_to('Edit', 'round/edit?id='.$round->getId(), array('class' => 'btn')) ?>
&nbsp;<?php echo link_to('List', 'round/list', array('class' => 'btn')) ?>
</div>
