<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 19:00:01
?>
<h1>View Round</h1>
<hr />
<table id="form">
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $round->getId() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $round->getName() ?></td>
</tr>
<tr>
<th>Type: </th>
<td><?php echo $round->getTypeText() ?></td>
</tr>
<tr>
<th>Preceded by round: </th>
<td><?php echo $round->getPrecededByRoundId() ?></td>
</tr>
<tr>
<th>Feedback Weightage: </th>
<td><?php echo $round->getFeedbackWeightage() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $round->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $round->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<div id="button">
<?php echo link_to('Edit', 'round/edit?id='.$round->getId()) ?>
&nbsp;<?php echo link_to('List', 'round/list') ?>
</div>
