<?php
// auto-generated by sfPropelCrud
// date: 2008/06/28 16:50:23
?>
<h1>View Details</h1>
<hr />
<table id="form">
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $adjudicator->getId() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $adjudicator->getName() ?></td>
</tr>
<tr>
<th>Test score: </th>
<td><?php echo $adjudicator->getTestScore() ?></td>
</tr>
<tr>
<th>Institution Id: </th>
<td><?php echo $adjudicator->getInstitutionId() ?></td>
</tr>
<tr>
<th>Institution Name: </th>
<td><?php echo $adjudicator->getInstitution()->getName() ?></td>
</tr>
<tr>
<th>Active: </th>
<td><?php echo $adjudicator->getActive() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $adjudicator->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $adjudicator->getUpdatedAt() ?></td>
</tr>
<tr>
	<th>Conflicts: </th>
	<td>
	<table>
		<?php $conflicts = $adjudicator->getAdjudicatorConflicts() ?>
		<?php foreach($conflicts as $aConflict): ?>
		<tr>
			<td> <?php echo $aConflict->getId(); ?> </td>
			<td> <?php echo	$aConflict->getTeam()->getName(); ?> </td>
			<td> <?php echo $aConflict->getTeam()->getInstitution()->getName(); ?> </td>
		</tr>
		<?php endforeach; ?>	  
	</table>
	</td>
</tr>
</tbody>
</table>
<hr />
<div id="button">
<?php echo link_to('Edit', 'adjudicator/edit?id='.$adjudicator->getId()) ?>
&nbsp;<?php echo link_to('List', 'adjudicator/list') ?>
&nbsp;<?php echo link_to('Show Feedback', 'adjudicator/showFeedback?id='.$adjudicator->getId()) ?>
</div>
