<?php
// auto-generated by sfPropelCrud
// date: 2008/06/03 03:45:14
?>
<h1>Show Venue</h1>
<hr />
<table id="form">
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $venue->getId() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $venue->getName() ?></td>
</tr>
<tr>
<th>Active: </th>
<td><?php echo $venue->getActive() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $venue->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $venue->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<div id="button">
<?php echo link_to('Edit', 'venue/edit?id='.$venue->getId()) ?>
&nbsp;<?php echo link_to('List', 'venue/list') ?>
</div>
