<?php
// auto-generated by sfPropelCrud
// date: 2008/06/28 16:36:40
?>
<h1>Debater</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Name</th>
  <th>Team Id</th>
  <th>Team Name</th>
  <th>Created at</th>
  <th>Updated at</th>
</tr>
</thead>
<tbody>
<?php foreach ($debaters as $debater): ?>
<tr>
    <td><?php echo link_to($debater->getId(), 'debater/show?id='.$debater->getId()) ?></td>
      <td><?php echo $debater->getName() ?></td>
      <td><?php echo $debater->getTeamId() ?></td>
	  <td><?php echo $debater->getTeam()->getName() ?></td>
      <td><?php echo $debater->getCreatedAt() ?></td>
      <td><?php echo $debater->getUpdatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
<div id="button">
	<?php echo link_to ('Create', 'debater/create') ?> &nbsp; <?php echo link_to ('Import from CSV', 'import/index?target_model=Debater'); ?>
</div>
