<script type="text/javascript">
jQuery(document).ready(function () {	
	jQuery("#subnav").hide();
	jQuery(".nav-admin").click(function() {
		jQuery("#subnav").toggle(300);
	});
});
</script>
<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 19:00:01
?>

<?php use_helper('Object') ?>

<?php echo form_tag('tournament/confirmFeedback') ?>

<h1> Feedback forms from <?php echo $team->getName(); ?> for <?php echo $round->getName();?></h1>
<hr />
<?php foreach($sf_request->getErrors() as $name => $error): ?>
    <li><h2>Error: <?php echo $error ?></h2></li>
  <?php endforeach; 
        //keep tracks of the number of adjudicators being feedbacked in this form
        $adjCount = 1;      
  ?>
<table id="form">
<tbody>
<?php foreach ($adjudicatorsToFeedback as $adjudicator): ?>
<tr>
	<td>		
		<?php                        
                        echo "<h2>Adjudicator  ". $adjCount. ": ";                        
			echo $adjudicator->getAdjudicator()->getName();
			echo "</h2>" 
		?>
	</td>
</tr>
<tr>
	<td>
		<?php 
			echo "<strong>Score:    </strong>";
                        //each judge being feedbacked receives his own score
			echo input_tag('score'.$adjCount, '', 'maxlength=1');
		?>
	</td>
</tr>
<tr>
	<td>
		<?php 
                        echo "<strong>Comments:    </strong>";
                        //each judge being feedbacked receives his own comment
			echo textarea_tag('comments'.$adjCount, "No Comment", 'size=60x10') ;
                 ?>
            <br><br>
	</td>
</tr>

<?php         
        echo input_hidden_tag('adjudicator'.$adjCount, $adjudicator->getAdjudicatorId()); 
        $adjCount++;
        endforeach;
        echo input_hidden_tag('adjCount', $adjCount);
?>

</tbody>
</table>
<?php echo input_hidden_tag('id', $round->getId()); ?>
<?php echo input_hidden_tag('team', $team->getId());?>
<?php echo submit_tag('Submit Feedback') ?>
