<script type="text/javascript">
jQuery(document).ready(function () {	
	jQuery("#subnav").hide();
	jQuery(".nav-admin").click(function() {
		jQuery("#subnav").toggle(300);
	});
});
</script>
<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 19:00:01
?>

<?php use_helper('Object') ?>

<?php echo form_tag('tournament/confirmTraineeFeedback') ?>

<h1> Feeback Entry Form </h1>
<?php foreach($sf_request->getErrors() as $name => $error): ?>
    <li><h2>Error: <?php echo $error ?></h2></li>
  <?php endforeach; ?>
<table>
<tbody>
<tr>
	<td>
		<?php 
			
			echo "Feedback For:    ";
			echo $allocation->getAdjudicatorRelatedByTraineeId()->getName(); 
		?>
	</td>
</tr>
<tr>
	<td>		
		<?php
			echo "Feedback From:   ";
			echo $allocation->getAdjudicatorRelatedByChairId()->getName(); 
			
		?>
	</td>
</tr>
<tr>
	<td>
		<?php 
			echo "Score:    ";
			echo input_tag('score', round($allocation->getAdjudicatorRelatedByTraineeId()->getScore()), 'maxlength=1') ;
		?>
	</td>
</tr>
<tr>
	<td>
		<?php 
			echo "Comments:    ";
			if(!$comments)
			{
				$comments = "No Comment";
			}
			echo input_tag('comments', $comments, 'size=40x40') ;
		?>
	</td>
</tr>



</tbody>
</table>
<?php echo input_hidden_tag('id', $round->getId()); ?>
<?php echo input_hidden_tag('trainee', $allocation->getAdjudicatorRelatedByTraineeId()->getId()); ?>
<?php echo input_hidden_tag('traineeAllocation', $allocation->getId()); ?>
<?php echo input_hidden_tag('chair', $allocation->getAdjudicatorRelatedByChairId()->getId()) ?>
<?php echo submit_tag('Submit Feedback') ?>

