<script type="text/javascript">
jQuery(document).ready(function () {	
	jQuery("#subnav").hide();
	jQuery(".nav-admin").click(function() {
		jQuery("#subnav").toggle(300);
	});
});
</script>
<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 19:00:01
?>

<?php use_helper('Object') ?>

<?php echo form_tag('tournament/confirmTraineeFeedback') ?>

<h1> Trainee Feedback Entry Form from <?php echo $chairAllocation->getAdjudicatorName(); ?> for <?php echo $round->getName();?></h1>
<?php foreach($sf_request->getErrors() as $name => $error): ?>
    <li><h2>Error: <?php echo $error ?></h2></li>
  <?php endforeach; ?>
<table>
<tbody>
    <?php $traineeCount = 1; foreach ($traineeAllocations as $trainee): ?>
    <tr>
            <td>		
                    <?php                        
                            echo "<h2>Trainee  ". $traineeCount. ": ";                        
                            echo $trainee->getAdjudicatorName();
                            echo "</h2>" 
                    ?>
            </td>
    </tr>
    <tr>
            <td>
                    <?php 
                            echo "<strong>Score:    </strong>";
                            //each judge being feedbacked receives his own score
                            echo input_tag('score'.$traineeCount, '', 'maxlength=1');
                    ?>
            </td>
    </tr>
    <tr>
            <td>
                    <?php 
                            echo "<strong>Comments:    </strong>";
                            //each judge being feedbacked receives his own comment
                            echo textarea_tag('comments'.$traineeCount, "No Comment", 'size=60x10') ;
                    ?>
                <br><br>
            </td>
    </tr>

<?php         
        echo input_hidden_tag('trainee'.$traineeCount, $trainee->getAdjudicatorId()); 
        $traineeCount++;       
        endforeach;
        echo input_hidden_tag('adjCount', $traineeCount);
?>

</tbody>
</table>
<?php echo input_hidden_tag('id', $round->getId()); ?>
<?php echo input_hidden_tag('chairAllocation', $chairAllocation->getId()) ?>
<?php echo submit_tag('Submit Feedback') ?>

