<script type="text/javascript">
jQuery(document).ready(function () {	
	jQuery("#subnav").hide();
	jQuery(".nav-admin").click(function() {
		jQuery("#subnav").toggle(300);
	});
});
</script>
<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 19:00:01
?>

<?php use_helper('Object') ?>

<?php echo form_tag('tournament/enterTraineeFeedback') ?>

<h1> Select a trainee </h1>
<table>
<tbody>
<tr>
	<th> Trainee Name </th>
<tr>
	<td>
		<?php 
			echo select_tag('traineeAllocation', objects_for_select($traineeAllocations, 'getId', 'getInfo'));
		?>
	</td>
</tr>


</tbody>
</table>
<?php echo input_hidden_tag('id', $round->getId()); ?>
<?php echo submit_tag('select') ?>

