<script type="text/javascript">
jQuery(document).ready(function () {	
	jQuery("#subnav").hide();
	jQuery(".nav-admin").click(function() {
		jQuery("#subnav").toggle(300);
	});
});
</script>
<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 19:00:01
?>

<?php use_helper('Object') ?>

<?php echo form_tag('tournament/enterTraineeFeedback') ?>

<h1> <?php echo $round->getName(); ?>  Trainee Feedback<br><br> Select the chair for whom the feedback is from </h1>
<table>
<tbody>
<tr>
	<th> Chair Name </th>
<tr>
	<td>
		<?php 
			echo select_tag('chairAllocation', objects_for_select($chairAllocations, 'getId', 'getAdjudicatorName'));
		?>
	</td>
</tr>


</tbody>
</table>
<?php echo input_hidden_tag('id', $round->getId()); ?>
<?php echo submit_tag('select') ?>

