<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 19:00:01
?>
<?php use_helper('Object') ?>

<?php echo form_tag('round/update') ?>

<?php echo object_input_hidden_tag($round, 'getId') ?>
<h1>Create/Edit Round</h1>
<hr />
<table id="form">
<tbody>
<tr>
  <th>Name <span class="red">*</span> :</th>
  <td><?php echo object_input_tag($round, 'getName', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Type <span class="red">*</span> :</th>
  <td><?php echo select_tag("type", options_for_select(array(Round::ROUND_TYPE_RANDOM => "Random", Round::ROUND_TYPE_PRELIMINARY => "Preliminary", Round::ROUND_TYPE_BUBBLE => "Bubble"), $sf_request->getParameter('type', $round->getType()))); ?></td>
</tr>
<tr>
  <th>Feedback Weightage <span class="red">*</span> :</th>
  <td><?php echo object_input_tag($round, 'getFeedbackWeightage', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Preceded by round <span class="red">*</span> :</th>
  <td><?php echo object_select_tag($round, 'getPrecededByRoundId', array (
  'related_class' => 'Round','text_method' => 'getName', 'include_blank' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<div id="button">
<?php echo submit_tag('Save') ?>
<?php if ($round->getId()): ?>
  &nbsp;<?php echo link_to('Delete', 'round/delete?id='.$round->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('Cancel', 'round/show?id='.$round->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancel', 'round/list') ?>
<?php endif; ?>
</div>
</form>
