<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 19:00:01
?>

<?php use_helper('Object') ?>

<?php echo form_tag('round/commitScores') ?>

<?php echo input_hidden_tag('govXref', $debate->getDebateTeamXref(1)->getId()) ?>
<?php echo input_hidden_tag('oppXref', $debate->getDebateTeamXref(2)->getId()) ?>
<?php echo input_hidden_tag('allocation', $allocation->getId()) ?>

<h1> Enter  The Scores </h1>
<br><br>
<table>
<tbody>
<?php
	$team = $debate->getTeam(1);
	$debaters = $team->getDebaters();
?>
<th>Government Team <?php echo $team->getName() ?></th>
<tr>
	<th>Prime Minister:</th>
	<td>
		<?php 	
			echo select_tag('gov1', objects_for_select($debaters, 'getId', 'getName'));
		?>
	</td>
	<td>
		<?php echo input_tag('gov1score', '', 'maxlength=4') ?>
	</td>
</tr>
<tr>
	<th>Deputy Prime Minister:</th>
	<td>
		<?php 		
			echo select_tag('gov2', objects_for_select($debaters, 'getId', 'getName'));
		?>
	</td>
	<td>
		<?php echo input_tag('gov2score', '', 'maxlength=4') ?>
	</td>
</tr>
</tr>
<tr>
	<th>Government Whip:</th>
	<td>
		<?php 
			echo select_tag('gov3', objects_for_select($debaters, 'getId', 'getName'));
		?>
	</td>
	<td>
		<?php echo input_tag('gov3score', '', 'maxlength=4') ?>
	</td>
</tr>
<tr>
	<th>Government Reply:</th>
	<td>
		<?php 	
			echo select_tag('gov4', objects_for_select($debaters, 'getId', 'getName'));
		?>
	</td>
	<td>
		<?php echo input_tag('gov4score', '', 'maxlength=4') ?>
	</td>
</tr>
<tr>
	<td>
		<br><br><br><br>
	</td>
</tr>
<?php 
	$team = $debate->getTeam(2);
	$debaters = $team->getDebaters();
?>
<th>Opposition Team <?php echo $team->getName() ?></th>
<tr>
	<th>Leader of Opposition:</th>
	<td>
		<?php 	
			echo select_tag('opp1', objects_for_select($debaters, 'getId', 'getName'));
		?>
	</td>
	<td>
		<?php echo input_tag('opp1score', '', 'maxlength=4') ?>
	</td>
</tr>
<tr>
	<th>Deputy Leader of Opposition:</th>
	<td>
		<?php 		
			echo select_tag('opp2', objects_for_select($debaters, 'getId', 'getName'));
		?>
	</td>
	<td>
		<?php echo input_tag('opp2score', '', 'maxlength=4') ?>
	</td>
</tr>
<tr>
	<th>Opposition Whip:</th>
	<td>
		<?php 
			echo select_tag('opp3', objects_for_select($debaters, 'getId', 'getName'));
		?>
	</td>
	<td>
		<?php echo input_tag('opp3score', '', 'maxlength=4') ?>
	</td>
</tr>
<tr>
	<th>Opposition Reply:</th>
	<td>
		<?php 		
			echo select_tag('opp4', objects_for_select($debaters, 'getId', 'getName'));
		?>
	</td>
	<td>
		<?php echo input_tag('opp4score', '', 'maxlength=4') ?>
	</td>
</tr>


</tbody>
</table>
<br><br><br>
<?php echo submit_tag('Submit Scores') ?>

