<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 18:55:06
?>
<?php use_helper('Object') ?>

<?php echo form_tag('institution/update') ?>

<?php echo object_input_hidden_tag($institution, 'getId') ?>
<h1>Edit Institution</h1>
<hr />
<table id="form">
<tbody>
<tr>
  <th>Code <span class="red">*</span> :</th>
  <td><?php echo object_input_tag($institution, 'getCode', array (
  'size' => 40,
)) ?></td>
</tr>
<tr>
  <th>Name <span class="red">*</span> :</th>
  <td><?php echo object_input_tag($institution, 'getName', array (
  'size' => 40,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<div id="button">
<?php echo submit_tag('Save') ?>
<?php if ($institution->getId()): ?>
  &nbsp;<?php echo link_to('Delete', 'institution/delete?id='.$institution->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('Cancel', 'institution/show?id='.$institution->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancel', 'institution/list') ?>
<?php endif; ?>
</div>
</form>
