<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 18:55:06
?>
<h1>View Institution</h1>

<?php if ($sf_flash->has("success")): ?>
<div class="alert-message success">
    <?php echo $sf_flash->get("success"); ?>
</div>
<?php endif; ?>

<div class="row">
    <div class="span-one-third"><strong>Id</strong></div>
    <div class="span-two-thirds"><?php echo $institution->getId(); ?></div>
</div>
<div class="row">
    <div class="span-one-third"><strong>Code</strong></div>
    <div class="span-two-thirds"><?php echo $institution->getCode(); ?></div>
</div>
<div class="row">
    <div class="span-one-third"><strong>Name</strong></div>
    <div class="span-two-thirds"><?php echo $institution->getName(); ?></div>
</div>
<div class="row">
    <div class="span-one-third"><strong>Created at</strong></div>
    <div class="span-two-thirds"><?php echo $institution->getCreatedAt(); ?></div>
</div>
<div class="row">
    <div class="span-one-third"><strong>Updated at</strong></div>
    <div class="span-two-thirds"><?php echo $institution->getUpdatedAt(); ?></div>
</div>
<div id="button">
<?php echo link_to('Edit', 'institution/edit?id='.$institution->getId(), array("class" => "btn")) ?>
&nbsp;<?php echo link_to('List', 'institution/list', array("class" => "btn")) ?>
</div>
