<?php
// auto-generated by sfPropelCrud
// date: 2008/06/03 03:45:14
?>
<h1>View Venue</h1>

<?php if ($sf_flash->has("success")): ?>
<div class="alert-message success">
    <?php echo $sf_flash->get("success"); ?>
</div>
<?php endif; ?>

<div class="row">
    <div class="span-one-third"><strong>Id</strong></div>
    <div class="span-two-thirds"><?php echo $venue->getId(); ?></div>
</div>
<div class="row">
    <div class="span-one-third"><strong>Name</strong></div>
    <div class="span-two-thirds"><?php echo $venue->getName(); ?></div>
</div>
<div class="row">
    <div class="span-one-third"><strong>Active</strong></div>
    <div class="span-two-thirds"><?php echo $venue->getActive(); ?></div>
</div>
<div class="row">
    <div class="span-one-third"><strong>Created at</strong></div>
    <div class="span-two-thirds"><?php echo $venue->getCreatedAt(); ?></div>
</div>
<div class="row">
    <div class="span-one-third"><strong>Updated at</strong></div>
    <div class="span-two-thirds"><?php echo $venue->getUpdatedAt(); ?></div>
</div>
<div id="button">
<?php echo link_to('Edit', 'venue/edit?id='.$venue->getId(), array('class' => 'btn')) ?>
&nbsp;<?php echo link_to('List', 'venue/list', array('class' => 'btn')) ?>
</div>
