<script type="text/javascript">
jQuery(document).ready(function () {	
	jQuery("#subnav").hide();
	jQuery(".nav-admin").click(function() {
		jQuery("#subnav").toggle(300);
	});
});
</script>
<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 19:00:01
?>

<?php use_helper('Object') ?>

<?php echo form_tag('tournament/confirmFeedback') ?>

<h1> Feeback Entry Form for <?php echo $adjudicator->getName(); ?></h1>
<hr />
<?php foreach($sf_request->getErrors() as $name => $error): ?>
    <li><h2>Error: <?php echo $error ?></h2></li>
  <?php endforeach; ?>
<table id="form">
<tbody>
<tr>
	<td>		
		<?php
			echo "Feedback From:   ";
			if($source == 1)
			{
				echo $team->getName();
				echo input_hidden_tag('team', $team->getId());
			}
			if($source == 2)
			{
				echo $feedbackingAdjudicator->getName();		
				echo input_hidden_tag('feedbackingAdjudicator',  $feedbackingAdjudicator->getId());			
			}
		?>
	</td>
</tr>
<tr>
	<td>
		<?php 
			echo "Score:    ";
			echo input_tag('score', '0', 'maxlength=1');
		?>
	</td>
</tr>
<tr>
	<td>
		<?php 
			echo "Comments:    ";
			if(!$comments)
			{
				$comments = "No Comment";
			}
			echo input_tag('comments', $comments, 'size=40x40') ;
		?>
	</td>
</tr>



</tbody>
</table>
<?php echo input_hidden_tag('id', $round->getId()); ?>
<?php echo input_hidden_tag('adjudicator', $adjudicator->getId()); ?>

<?php echo input_hidden_tag('source', $source) ?>
<?php echo input_hidden_tag('sourceId', $feedbackFrom[0]->getId()) ?>
<?php echo submit_tag('Submit Feedback') ?>

