<script type="text/javascript">
jQuery(document).ready(function () {	
	jQuery("#subnav").hide();
	jQuery(".nav-admin").click(function() {
		jQuery("#subnav").toggle(300);
	});
});
</script>
<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 19:00:01
?>

<?php use_helper('Object') ?>

<?php echo form_tag('tournament/selectFeedbackSource') ?>

<h1> Select an Adjudicator </h1>
<hr />
<table id="form">
<tbody>
<tr>
	<th> Adjudicator Name </th>
	<th> Feedback Source </th>
<tr>
	<td valign="top">
		<?php 
			echo select_tag('adjudicator', objects_for_select($adjudicators, 'getId', 'getName'));
		?>
	</td>
	<td>
		<?php 
			echo radiobutton_tag('source', '1', false);			
			echo "   Teams Adjudicated ";
			echo '<br/><br/>';
		?>
		<?php
			echo radiobutton_tag('source', '2', false);			
			echo "   Fellow Panelists ";
		?>
	</td>
</tr>


</tbody>
</table>
<?php echo input_hidden_tag('id', $round->getId()); ?>
<?php echo submit_tag('select') ?>

