<script type="text/javascript">
jQuery(document).ready(function () {	
	jQuery("#subnav").hide();
	jQuery(".nav-admin").click(function() {
		jQuery("#subnav").toggle(300);
	});
});
</script>
<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 19:00:01
?>

<?php use_helper('Object') ?>

<?php echo form_tag('tournament/enterFeedback') ?>

<h1> Feeback Submitted By: </h1>
<hr />

<table id="form">
<tbody>
<tr>
	<td>
		<?php
			if($source == 1)
			{
				echo select_tag('team', objects_for_select($teams, 'getId', 'getName'));

			}
			if($source == 2)
			{
				echo select_tag('feedbackingAdjudicator', objects_for_select($feedbackingAdjudicators, 'getId', 'getName'));				
			}
		?>
	</td>
</tr>


</tbody>
</table>
<?php echo input_hidden_tag('id', $round->getId()); ?>
<?php echo input_hidden_tag('adjudicator', $adjudicator->getId()); ?>
<?php echo input_hidden_tag('source', $source) ?>
<?php echo submit_tag('select') ?>

