<?php
// auto-generated by sfPropelCrud
// date: 2008/06/28 16:50:23
?>
<?php use_helper('Object') ?>

<?php echo form_tag('adjudicator/createConflict') ?>

<?php echo object_input_hidden_tag($adjudicator, 'getId') ?>
<h1>Add Conflict</h1>
<hr />
<table id="form">
<tbody>
<tr>
  <th>Adjudicator Name:</th>
  <td><?php echo $adjudicator->getName() ?></td>
</tr>
<tr>
  <th>Adjudicator Institution:</th>
  <td><?php echo $adjudicator->getInstitution()->getName() ?></td>
</tr>
<tr>
  <th>Conflicting Team:</th>
  <td><?php echo select_tag('teamId', objects_for_select($teams, 'getId', 'getName')) ?></td>
</tr>

</tbody>
</table>

<hr />

<div id="button">
<?php echo submit_tag('Save') ?>
<?php if ($adjudicator->getId()): ?>
  &nbsp;<?php echo link_to('Cancel', 'adjudicator/edit?id='.$adjudicator->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancel', 'adjudicator/list') ?>
<?php endif; ?>
</div>
</form>
