<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 18:59:53
?>
<?php use_helper('Object') ?>

<?php echo form_tag('team/update') ?>

<?php echo object_input_hidden_tag($team, 'getId') ?>
<h1>Create/Edit Team</h1>
<hr />

<table id="form">
	<tbody>
		<tr>
			<th>Name <span class="red">* </span> :</th>
			<td>
			<?php echo object_input_tag($team, 'getName', array ('size' => 20,)) ?>
			</td>
		</tr>
			<th>Institution <span class="red">*</span> :</th>
			<td>
			<?php echo object_select_tag($team, 'getInstitutionId', array (
			  'related_class' => 'Institution',
			  'text_method' => 'getName',)) ?>			
			</td>
		<tr>
		</tr>
			<th>Swing <span class="red">*</span> :</th>
			<td><?php echo object_checkbox_tag($team, 'getSwing', array ()) ?></td>
		<tr>
			<th>Active <span class="red">*</span> :</th>
			<td><?php echo object_checkbox_tag($team, 'getActive', array ()) ?></td>
		</tr>
	</tbody>
</table>

<table>
    <thead>
        <tr>
            <th>No</th>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
<?php
foreach($team->getDebaters() as $count => $debater)
{
?>
        <tr>
            <td><?php echo $count + 1; ?></td>
            <td><?php echo input_tag('debaters['.$count.'][name]', $debater->getName()); ?></td>
			<?php echo input_hidden_tag('debaters['.$count.'][debater_id]', $debater->getId()) ?>
        </tr>
<?php
}
?>
    </tbody>
</table>

<hr />
<div id="button">
<?php echo submit_tag('Save') ?>
<?php if ($team->getId()): ?>
  &nbsp;<?php echo link_to('Delete', 'team/delete?id='.$team->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('Cancel', 'team/show?id='.$team->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancel', 'team/list') ?>
<?php endif; ?>
</div>
</form>
