<?php
// auto-generated by sfPropelCrud
// date: 2008/06/28 16:36:40
?>
<?php

/**
 * debater actions.
 *
 * @package    stab
 * @subpackage debater
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class debaterActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('debater', 'list');
  }

  public function executeList()
  {
    $this->debaters = DebaterPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->debater = DebaterPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->debater);
  }

  public function executeCreate()
  {
    $this->debater = new Debater();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->debater = DebaterPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->debater);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $debater = new Debater();
    }
    else
    {
      $debater = DebaterPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($debater);
    }

    $debater->setId($this->getRequestParameter('id'));
    $debater->setName($this->getRequestParameter('name'));
    $debater->setTeamId($this->getRequestParameter('team_id') ? $this->getRequestParameter('team_id') : null);

    $debater->save();

    return $this->redirect('debater/show?id='.$debater->getId());
  }

  public function executeDelete()
  {
    $debater = DebaterPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($debater);

    $debater->delete();

    return $this->redirect('debater/list');
  }
}
