<?php
// auto-generated by sfPropelCrud
// date: 2008/06/28 16:50:23
?>
<?php use_helper('Object') ?>

<?php echo form_tag('adjudicator/update') ?>

<?php echo object_input_hidden_tag($adjudicator, 'getId') ?>

<h1>Create/Edit Adjudicator</h1>
<hr />
<table id="form">
<tbody>
<tr>
  <th>Name <span class="red">*</span> :</th>
  <td><?php echo object_input_tag($adjudicator, 'getName', array (
  'size' => 60,
)) ?></td>
</tr>
<tr>
  <th>Test score <span class="red">*</span> :</th>
  <td><?php echo object_input_tag($adjudicator, 'getTestScore', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Institution <span class="red">*</span> :</th>
  <td><?php echo object_select_tag($adjudicator, 'getInstitutionId', array (
  'related_class' => 'Institution',
  'text_method' => 'getName',
)) ?></td>
</tr>
<tr>
  <th>Active <span class="red">*</span> :</th>
  <td><?php echo object_checkbox_tag($adjudicator, 'getActive', array (
)) ?></td>
</tr>
<tr>
	<th valign="top">Conflicts: </th>
	<td>
	<table cellpadding=0 cellspacing=0>
		<?php $conflicts = $adjudicator->getAdjudicatorConflicts() ?>
		<?php foreach($conflicts as $aConflict): ?>
		<tr>
			<td> <?php echo $aConflict->getId(); ?> </td>
			<td> <?php echo	$aConflict->getTeam()->getName(); ?> </td>
			<td> <?php echo $aConflict->getTeam()->getInstitution()->getName(); ?> </td>
			<?php if($aConflict->getTeam()->getInstitutionId() != $aConflict->getAdjudicator()->getInstitutionId()): ?>
			<td> <?php echo link_to('delete', 'adjudicator/deleteConflict?conflictId='.$aConflict->getId(), 
					'post=true&confirm=Are you sure?') ?></td>
			<?php endif; ?>
		</tr>
		<?php endforeach; ?>
		<tr>
			<td><div id="button">
				<?php echo link_to('Add conflict', 'adjudicator/addConflict?id='.$adjudicator->getId()) ?>
				</div>
			</td>
		</tr>		  
	</table>
	</td>
</tr>
</tbody>
</table>

<hr />
<div id="button">
<?php echo submit_tag('Save') ?>
<?php if ($adjudicator->getId()): ?>
  &nbsp;<?php echo link_to('Delete', 'adjudicator/delete?id='.$adjudicator->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('Cancel', 'adjudicator/show?id='.$adjudicator->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancel', 'adjudicator/list') ?>
<?php endif; ?>
</div>
</form>
