<?php
// auto-generated by sfPropelCrud
// date: 2008/06/28 16:50:23
?>
<h1>Adjudicator</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Name</th>
  <th>Test score</th>
  <th>Score</th>
  <th>Institution Id</th>
  <th>Institution Name</th>
  <th>Active</th>
  <th>Created at</th>
  <th>Updated at</th>
</tr>
</thead>
<tbody>
<?php 
	$adjScores = array();
	foreach($adjudicators as $number => $adjudicator)
	{
		$adjScores[$number] = $adjudicator->getScore($round);
	}
	arsort($adjScores);
	
	
?>
<?php foreach ($adjScores as $number => $sScore): ?>
<?php $adjudicator = $adjudicators[$number];?>
<tr>
    <td><?php echo link_to($adjudicator->getId(), 'adjudicator/show?id='.$adjudicator->getId()) ?></td>
      <td><?php echo $adjudicator->getName() ?></td>
      <td><?php echo $adjudicator->getTestScore() ?></td>
	  <td><?php echo $adjudicator->getScore($round) ?></td>
      <td><?php echo $adjudicator->getInstitutionId() ?></td>
	  <td><?php echo $adjudicator->getInstitution()->getName() ?> </td>
      <td><?php echo $adjudicator->getActive() ?></td>
      <td><?php echo $adjudicator->getCreatedAt() ?></td>
      <td><?php echo $adjudicator->getUpdatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<div id="button">
<?php echo link_to ('Create', 'adjudicator/create') ?>&nbsp;<?php echo link_to ('Import from CSV', 'import/index?target_model=Adjudicator'); ?>
</div>
