<?php
// auto-generated by sfPropelCrud
// date: 2008/06/28 16:50:23
?>
<h1>Adjudicator</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Round</th>
  <th>Feedback Source</th>
  <th>Score</th>
  <th>Comments</th>
</tr>
</thead>
<tbody>
<?php foreach ($feedbackSheets as $aFeedbackSheet): ?>
<tr>
	<td><?php echo $aFeedbackSheet->getId(); //link_to($aFeedbackSheet->getId(), 'adjudicator/editFeedback?id='.$aFeedbackSheet->getId()) ?></td>
	<?php $aFeedbackSheet->getAdjudicatorAllocationId() ? $source = 0 : $source = 1;?>
		
    <?php if($source == 0): ?>
		<td><?php echo $aFeedbackSheet->getAdjudicatorAllocation()->getDebate()->getRound()->getName() ?></td>
	<?php endif; ?>
	<?php if($source == 1): ?>
		<td><?php echo $aFeedbackSheet->getDebateTeamXref()->getDebate()->getRound()->getName() ?></td>
	<?php endif; ?>
	<?php if($source == 0): ?>
		<td><?php echo $aFeedbackSheet->getAdjudicatorAllocation()->getAdjudicator()->getName() ?></td>
	<?php endif; ?>
	<?php if($source == 1): ?>
		<td><?php echo $aFeedbackSheet->getDebateTeamXref()->getTeam()->getName() ?></td>
	<?php endif; ?>
	<td><?php echo $aFeedbackSheet->getScore() ?></td>
	<td><?php echo $aFeedbackSheet->getComments() ?></td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<br><br>
<?php echo link_to('back', 'adjudicator/show?id='.$adjudicator->getId()); ?>

