<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 18:59:53
?>
<h1>Adjudicator</h1>
<table>
<thead>
<tr>
  <th>Adjudicator Name</th>
  <th>Team Adjudicated</th>
</tr>
</thead>
<tbody>
<?php foreach ($adjudicators as $anAdjudicator): ?>
<tr>
    <td><?php echo $anAdjudicator->getName() ?></td>
	<td>
		<?php 
			$teamsAdjudicated = $anAdjudicator->getTeamsAdjudicated();
			foreach($teamsAdjudicated as $aTeamAdjudicated)
			{
				echo $aTeamAdjudicated->getName().'<br>';				
			}	
		?>
	</td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
