<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 19:00:01
?>

<?php use_helper('Object') ?>

<?php echo form_tag('round/enterScores3') ?>

<?php echo object_input_hidden_tag($debate, 'getId') ?>

<h1> Select an adjudicator </h1>
<table>
<tbody>
<tr>
	<td>
		<?php 
			$allocations = $debate->getUnscoredAdjudicatorAllocations();
			echo select_tag('allocation', objects_for_select($allocations, 'getId', 'getAdjudicatorName'));
		?>

	</td>
</tr>


</tbody>
</table>
<?php echo submit_tag('select') ?>

