<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 18:59:53
?>
<h1>View Team</h1>
<hr />
<table id="form">
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $team->getId() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $team->getName() ?></td>
</tr>
<tr>
<th>Institution Id: </th>
<td><?php echo $team->getInstitutionId() ?></td>
</tr>
<tr>
<th>Institution Name: </th>
<td><?php echo $team->getInstitution()->getName() ?></td>
</tr>
<tr>
<th>Swing: </th>
<td><?php echo $team->getSwing() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $team->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $team->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<div id="button">
<?php echo link_to('Edit', 'team/edit?id='.$team->getId()) ?>
&nbsp;<?php echo link_to('List', 'team/list') ?>
</div>
