<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 18:59:53
?>
<h1>Team</h1>
<table>
<thead>
<tr>
  <th>Team Name</th>
  <th>Team Met</th>
</tr>
</thead>
<tbody>
<?php foreach ($teams as $team): ?>
<tr>
    <td><?php echo $team->getName() ?></td>
	<td>
		<?php 
			$teamsMet = $team->getTeamsDebated();
			foreach($teamsMet as $aTeamMet)
			{
				echo $aTeamMet->getName().'<br>';
			}			
		?>
	</td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
