<script type="text/javascript">
jQuery(document).ready(function () {	
	jQuery("#subnav").hide();
	jQuery(".nav-admin").click(function() {
		jQuery("#subnav").toggle(300);
	});
});
</script>
<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 18:59:53
?>
<?php ini_set('memory_limit', '128M') //the sort is very memory intensive ?>
<h1>Team Rankings</h1>
<table>
<thead>
<tr>
  <th>Rank</th>
  <th>Name</th>
  <th>Team Scores</th>
  <th>Speaker Scores</th>
  <th>Margin</th>
  <th>Times Aff</th>
</tr>
</thead>
<tbody>
<?php $count = 1 ?>

<?php foreach ($teamScores as $teamScore): ?>

<tr>
    <td><?php echo $count++ ?></td>
      <td><?php echo TeamPeer::retrieveByPk($teamScore->getTeamId())->getName() ?></td>
      <td><?php echo $teamScore->getTotalTeamScore() ?></td>
	  <td><?php echo $teamScore->getTotalSpeakerScore()  ?></td>
	  <td><?php echo $teamScore->getTotalMargin()  ?></td>
	  <td><?php echo $teamScore->getTeam()->getTotalAffs() ?> </td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
<div id="button">
<?php echo link_to ('create', 'team/create') ?>
</div>
