<?php
// auto-generated by sfPropelCrud
// date: 2008/06/03 03:45:14
?>
<h1>Venue</h1>

<?php if ($sf_flash->has("success")): ?>
<div class="alert-message success">
    <?php echo $sf_flash->get("success"); ?>
</div>
<?php endif; ?>

<table class="bordered-table zebra-striped">
<thead>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Active</th>
        <th>Priority</th>
        <th>Created at</th>
        <th>Updated at</th>
    </tr>
</thead>
<tbody>
<?php foreach ($venues as $venue): ?>
    <tr>
        <td><?php echo $venue->getId()?>
        <td><?php echo link_to($venue->getName(), 'venue/show?id='.$venue->getId()) ?></td>
        <td><?php echo $venue->getActive() ?></td>
        <td><?php echo $venue->getPriority() ?></td>
        <td><?php echo $venue->getCreatedAt() ?></td>
        <td><?php echo $venue->getUpdatedAt() ?></td>
    </tr>
<?php endforeach; ?>
</tbody>
</table>

<br clear="all" />
<div id="button">
<?php echo link_to ('Create', 'venue/create', array('class' => 'btn')); ?> &nbsp; <?php echo link_to ('Import from CSV', 'import/index?target_model=Venue', array('class' => 'btn')); ?>
</div>
