<?php
// auto-generated by sfPropelCrud
// date: 2008/06/03 03:45:14
?>

<script type="text/javascript">

</script>
<h1>Venue</h1>
<table>
<thead>
<tr>
  <th>Id</th>
  <th>Name</th>
  <th>Active</th>
  <th>Priority</th>
  <th>Created at</th>
  <th>Updated at</th>
</tr>
</thead>
<tbody>
<?php foreach ($venues as $venue): ?>
<tr>
    <td><?php echo link_to($venue->getId(), 'venue/show?id='.$venue->getId()) ?></td>
      <td><?php echo $venue->getName() ?></td>
      <td><?php echo $venue->getActive() ?></td>
      <td><?php echo $venue->getPriority() ?></td>
      <td><?php echo $venue->getCreatedAt() ?></td>
      <td><?php echo $venue->getUpdatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<br clear="all" />
<div id="button">
<?php echo link_to ('Create', 'venue/create'); ?> &nbsp; <?php echo link_to ('Import from CSV', 'import/index?target_model=Venue'); ?>
</div>
