<script type="text/javascript">
jQuery(document).ready(function () {	
	jQuery("#subnav").hide();
	jQuery(".nav-admin").click(function() {
		jQuery("#subnav").toggle(300);
	});
});
</script>
<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 18:59:53
?>
<?php ini_set('memory_limit', '512M') //the sort is very memory intensive ?>
<h1>Debater Ranks</h1>
<table>
<thead>
<tr>
  <th>Rank</th>
  <th>Name</th>
  <th>Team</th>
  <th>Total Speaker Scores</th>
</tr>
</thead>
<tbody>
<?php $count = 1 ?>
<?php foreach ($speakerScores as $speakerScore): ?>
<tr>
    <td><?php echo $count++ ?></td>
	<?php $debater = DebaterPeer::retrieveByPk($speakerScore->getDebaterId()); ?>
      <td><?php echo $debater->getName() ?></td>
	  <td><?php echo $debater->getTeam()->getName() ?></td>
      <td><?php echo $speakerScore->getTotalSpeakerScore() ?> </td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
<div id="button">
<?php echo link_to ('back', 'post_tournament/index') ?>
</div>
