<?php
// auto-generated by sfPropelCrud
// date: 2008/06/28 16:36:40
?>
<?php use_helper('Object') ?>

<?php echo form_tag('debater/update') ?>

<?php echo object_input_hidden_tag($debater, 'getId') ?>

<h1>New Debater</h1>
<hr />
<table id="form">
<tbody>
<tr>
  <th>Name <span class="red">*</span> :</th>
  <td><?php echo object_input_tag($debater, 'getName', array (
  'size' => 60,
)) ?></td>
</tr>
<tr>
  <th>Team:</th>
  <td><?php echo object_select_tag($debater, 'getTeamId', array (
  'related_class' => 'Team',
  'include_blank' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />

<div id="button">
<?php echo submit_tag('Save') ?>
<?php if ($debater->getId()): ?>
  &nbsp;<?php echo link_to('Delete', 'debater/delete?id='.$debater->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('Cancel', 'debater/show?id='.$debater->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('Cancel', 'debater/list') ?>
<?php endif; ?>
</div>
</form>
