<?php
// auto-generated by sfPropelCrud
// date: 2008/06/28 16:36:40
?>
<h1>View Debater</h1>
<hr />

<table id="form">
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $debater->getId() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $debater->getName() ?></td>
</tr>
<tr>
<th>Team Id: </th>
<td><?php echo $debater->getTeamId() ?></td>
</tr>
<tr>
<th>Team Name: </th>
<td><?php echo $debater->getTeam()->getName() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $debater->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $debater->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<div id="button">
<?php echo link_to('Edit', 'debater/edit?id='.$debater->getId()) ?>
&nbsp;<?php echo link_to('List', 'debater/list') ?>
</div>
